/**
 * Demo duomenys iš mockup'o — rodomi tik tol, kol nepaleistas tikras importas
 * („Atnaujinti duomenis" nustatymuose). Tikri žaidėjai ateina iš `merge.ts`.
 */

import type { League, Player, Position, Status, Tier } from "./types";

/** [vardas, poz, komanda, pernykštė komanda, pernykštė lyga, min, fp, būklė, pakopa] */
type Row = [string, Position, string, string, League, number, number, Status, Tier];

const RAW: Row[] = [
  ["Sasha Vezenkov", "F", "Olympiacos", "Olympiacos", "EL", 28.4, 22.6, "ready", 1],
  ["Vasilije Micic", "G", "Hapoel Tel Aviv", "Phoenix Suns", "kita", 18.9, 14.1, "ready", 2],
  ["Mathias Lessort", "C", "Panathinaikos", "Panathinaikos", "EL", 22.1, 19.8, "doubtful", 1],
  ["Jonas Valanciunas", "C", "Zalgiris", "Denver Nuggets", "kita", 16.2, 15.4, "ready", 2],
  ["Tornike Shengelia", "F", "Virtus Bologna", "Virtus Bologna", "EL", 25.0, 18.9, "ready", 1],
  ["Kendrick Nunn", "G", "Panathinaikos", "Panathinaikos", "EL", 28.8, 21.2, "ready", 1],
  ["Nadir Hifi", "G", "Paris Basketball", "Paris Basketball", "EL", 26.4, 17.5, "ready", 2],
  ["Shane Larkin", "G", "Anadolu Efes", "Anadolu Efes", "EL", 27.2, 18.0, "doubtful", 2],
  ["Walter Tavares", "C", "Real Madrid", "Real Madrid", "EL", 20.6, 17.3, "ready", 1],
  ["Facundo Campazzo", "G", "Real Madrid", "Real Madrid", "EL", 26.9, 17.9, "ready", 1],
  ["Dzanan Musa", "F", "Real Madrid", "Real Madrid", "EL", 25.1, 16.4, "ready", 2],
  ["Rokas Jokubaitis", "G", "Bayern Munich", "Bayern Munich", "EL", 24.3, 14.8, "ready", 2],
  ["Azuolas Tubelis", "F", "Zalgiris", "Zalgiris", "EL", 23.6, 13.9, "ready", 2],
  ["Kostas Sloukas", "G", "Panathinaikos", "Panathinaikos", "EL", 24.0, 14.2, "ready", 2],
  ["Nikola Milutinov", "C", "Olympiacos", "Olympiacos", "EL", 21.4, 16.1, "ready", 1],
  ["Evan Fournier", "G", "Olympiacos", "Olympiacos", "EL", 22.8, 13.0, "ready", 3],
  ["Thomas Walkup", "G", "Olympiacos", "Olympiacos", "EL", 24.6, 12.4, "ready", 3],
  ["Kostas Papanikolaou", "F", "Olympiacos", "Olympiacos", "EL", 18.2, 7.6, "out", 4],
  ["Moustapha Fall", "C", "Olympiacos", "Olympiacos", "EL", 15.9, 9.8, "ready", 3],
  ["Isaiah Canaan", "G", "Olympiacos", "Hapoel Jerusalem", "kita", 22.0, 12.9, "ready", 3],
  ["Mike James", "G", "AS Monaco", "AS Monaco", "EL", 27.5, 19.4, "ready", 1],
  ["Elie Okobo", "G", "AS Monaco", "AS Monaco", "EL", 25.8, 15.2, "ready", 2],
  ["Alpha Diallo", "F", "AS Monaco", "AS Monaco", "EL", 24.1, 13.6, "ready", 2],
  ["Donatas Motiejunas", "C", "AS Monaco", "AS Monaco", "EL", 17.4, 9.1, "doubtful", 3],
  ["Matthew Strazel", "G", "AS Monaco", "AS Monaco", "EL", 22.7, 10.8, "ready", 3],
  ["Nikola Mirotic", "F", "AS Monaco", "AS Monaco", "EL", 19.3, 12.7, "doubtful", 3],
  ["Tomas Satoransky", "G", "FC Barcelona", "FC Barcelona", "EL", 24.4, 12.1, "ready", 3],
  ["Kevin Punter", "G", "FC Barcelona", "FC Barcelona", "EL", 26.0, 15.7, "ready", 2],
  ["Nicolas Laprovittola", "G", "FC Barcelona", "FC Barcelona", "EL", 23.9, 13.2, "ready", 2],
  ["Jan Vesely", "C", "FC Barcelona", "FC Barcelona", "EL", 18.6, 11.4, "out", 4],
  ["Willy Hernangomez", "C", "FC Barcelona", "FC Barcelona", "EL", 17.8, 14.0, "ready", 2],
  ["Alex Abrines", "F", "FC Barcelona", "FC Barcelona", "EL", 20.2, 9.3, "ready", 3],
  ["Nigel Hayes-Davis", "F", "Fenerbahce", "Fenerbahce", "EL", 27.9, 18.2, "ready", 1],
  ["Nicolo Melli", "F", "Fenerbahce", "Fenerbahce", "EL", 22.3, 12.6, "ready", 3],
  ["Wade Baldwin", "G", "Fenerbahce", "Fenerbahce", "EL", 24.7, 15.9, "doubtful", 2],
  ["Johnathan Motley", "C", "Fenerbahce", "Fenerbahce", "EL", 21.0, 15.1, "ready", 2],
  ["Marko Guduric", "G", "Fenerbahce", "Fenerbahce", "EL", 21.6, 10.4, "ready", 3],
  ["Devon Hall", "G", "Fenerbahce", "Fenerbahce", "EL", 19.1, 7.8, "ready", 4],
  ["Tarik Biberovic", "F", "Fenerbahce", "Fenerbahce", "EL", 20.8, 9.7, "ready", 3],
  ["Jordan Loyd", "G", "Anadolu Efes", "Anadolu Efes", "EL", 25.3, 15.3, "ready", 2],
  ["Rodrigue Beaubois", "G", "Anadolu Efes", "Anadolu Efes", "EL", 23.2, 12.8, "doubtful", 3],
  ["Errick McCollum", "G", "Anadolu Efes", "Bahcesehir", "EC", 26.8, 16.2, "ready", 2],
  ["Rolands Smits", "F", "Anadolu Efes", "Anadolu Efes", "EL", 19.7, 8.9, "ready", 4],
  ["Vincent Poirier", "C", "Anadolu Efes", "Anadolu Efes", "EL", 18.4, 11.8, "ready", 3],
  ["Marco Belinelli", "G", "Virtus Bologna", "Virtus Bologna", "EL", 18.0, 7.4, "ready", 4],
  ["Achille Polonara", "F", "Virtus Bologna", "Virtus Bologna", "EL", 20.4, 10.1, "out", 4],
  ["Isaia Cordinier", "G", "Virtus Bologna", "Virtus Bologna", "EL", 24.9, 14.6, "ready", 2],
  ["Daniel Hackett", "G", "Virtus Bologna", "Virtus Bologna", "EL", 17.6, 6.9, "doubtful", 4],
  ["Will Clyburn", "F", "Virtus Bologna", "Anadolu Efes", "EL", 21.2, 11.6, "ready", 3],
  ["Laurynas Birutis", "C", "Zalgiris", "Zalgiris", "EL", 16.8, 10.9, "ready", 3],
  ["Sylvain Francisco", "G", "Zalgiris", "Zalgiris", "EL", 26.2, 16.8, "ready", 1],
  ["Ignas Brazdeikis", "F", "Zalgiris", "Zalgiris", "EL", 22.5, 12.3, "ready", 3],
  ["Arnas Butkevicius", "F", "Zalgiris", "Zalgiris", "EL", 17.2, 5.8, "ready", 4],
  ["Deividas Sirvydis", "F", "Zalgiris", "Rytas Vilnius", "kita", 24.0, 11.2, "ready", 3],
  ["Markus Howard", "G", "Baskonia", "Baskonia", "EL", 24.2, 15.6, "ready", 2],
  ["Tadas Sedekerskis", "F", "Baskonia", "Baskonia", "EL", 22.9, 11.9, "ready", 3],
  ["Khalifa Diop", "C", "Baskonia", "Baskonia", "EL", 16.4, 9.4, "ready", 3],
  ["Luka Samanic", "F", "Baskonia", "Baskonia", "EL", 20.1, 10.6, "ready", 3],
  ["Trent Forrest", "G", "Baskonia", "Baskonia", "EL", 21.8, 9.9, "doubtful", 4],
  ["Roman Sorkin", "C", "Maccabi Tel Aviv", "Maccabi Tel Aviv", "EL", 19.4, 11.1, "ready", 3],
  ["Lorenzo Brown", "G", "Maccabi Tel Aviv", "Maccabi Tel Aviv", "EL", 25.6, 14.9, "ready", 2],
  ["Jaylen Hoard", "F", "Maccabi Tel Aviv", "Maccabi Tel Aviv", "EL", 23.4, 13.4, "ready", 2],
  ["Tamir Blatt", "G", "Maccabi Tel Aviv", "Maccabi Tel Aviv", "EL", 20.6, 8.6, "ready", 4],
  ["Carlik Jones", "G", "Crvena Zvezda", "Crvena Zvezda", "EL", 26.6, 17.1, "ready", 1],
  ["Nikola Kalinic", "F", "Crvena Zvezda", "Crvena Zvezda", "EL", 21.4, 9.2, "ready", 4],
  ["Joel Bolomboy", "C", "Crvena Zvezda", "Crvena Zvezda", "EL", 18.8, 11.7, "doubtful", 3],
  ["Nemanja Nedovic", "G", "Crvena Zvezda", "Crvena Zvezda", "EL", 19.6, 9.6, "ready", 4],
  ["Carsen Edwards", "G", "Partizan", "Partizan", "EL", 25.4, 16.6, "ready", 2],
  ["Sterling Brown", "F", "Partizan", "Partizan", "EL", 22.0, 11.3, "ready", 3],
  ["Duane Washington", "G", "Partizan", "Partizan", "EL", 23.8, 13.7, "ready", 2],
  ["Bruno Fernando", "C", "Partizan", "Real Betis", "kita", 18.2, 10.2, "ready", 3],
  ["Vladimir Lucic", "F", "Partizan", "Bayern Munich", "EL", 23.1, 11.5, "ready", 3],
  ["Andreas Obst", "G", "Bayern Munich", "Bayern Munich", "EL", 24.8, 12.2, "ready", 3],
  ["Serge Ibaka", "C", "Bayern Munich", "Bayern Munich", "EL", 15.6, 8.4, "doubtful", 4],
  ["Nick Weiler-Babb", "G", "Bayern Munich", "Bayern Munich", "EL", 23.6, 10.7, "ready", 3],
  ["Justinian Jessup", "F", "Bayern Munich", "Ulm", "kita", 22.4, 10.3, "ready", 3],
  ["Yam Madar", "G", "Paris Basketball", "Paris Basketball", "EL", 22.6, 11.8, "ready", 3],
  ["Mikael Jantunen", "F", "Paris Basketball", "Paris Basketball", "EL", 21.9, 10.9, "ready", 3],
  ["Amath M\u2019Baye", "F", "Paris Basketball", "Paris Basketball", "EL", 18.6, 7.2, "ready", 4],
  ["Ismael Kamagate", "C", "Paris Basketball", "Paris Basketball", "EL", 17.9, 10.5, "ready", 3],
  ["T.J. Shorts", "G", "Panathinaikos", "Paris Basketball", "EL", 26.1, 16.9, "ready", 1],
  ["Cedi Osman", "F", "Panathinaikos", "Panathinaikos", "EL", 20.9, 10.1, "ready", 3],
  ["Jerian Grant", "G", "Panathinaikos", "Panathinaikos", "EL", 18.3, 7.9, "ready", 4],
  ["Dinos Mitoglou", "F", "Panathinaikos", "Panathinaikos", "EL", 19.8, 9.5, "doubtful", 4],
  ["Omer Yurtseven", "C", "Panathinaikos", "Utah Jazz", "kita", 15.2, 8.8, "ready", 3],
  ["Ercan Osmani", "F", "Anadolu Efes", "Bursaspor", "kita", 24.4, 13.1, "ready", 2],
  ["Miro Bilan", "C", "Dubai BC", "Cedevita Olimpija", "kita", 20.4, 13.8, "ready", 2],
  ["Dwayne Bacon", "G", "Dubai BC", "Bahcesehir", "EC", 27.0, 15.8, "ready", 2],
  ["Justin Anderson", "F", "Dubai BC", "Dubai BC", "kita", 23.2, 12.0, "ready", 3],
  ["Filip Petrusev", "C", "Dubai BC", "Dubai BC", "kita", 21.0, 13.3, "ready", 2],
  ["Kristers Zoriks", "G", "Zalgiris", "Cibona", "-", 0, 6.4, "ready", 3],
  ["Marek Blazevic", "C", "Zalgiris", "Riesen Ludwigsburg", "-", 0, 5.9, "ready", 3],
  ["Gytis Radzevicius", "F", "Zalgiris", "Rytas Vilnius", "-", 0, 4.8, "ready", 4],
  ["Sasu Salin", "G", "Dubai BC", "Joventut", "-", 0, 4.2, "ready", 4],
  ["Lucas Langarita", "G", "Baskonia", "Zaragoza", "-", 0, 5.4, "ready", 3],
  ["Petar Popovic", "F", "Partizan", "Mega", "-", 0, 3.9, "ready", 4],
];

export const LEAGUE_LABEL: Record<League, string> = {
  EL: "Eurolyga",
  EC: "EuroCup",
  kita: "kita lyga",
  "-": "nėra duomenų",
};

export const PLAYERS: Player[] = RAW.map(
  ([name, pos, team, lastTeam, lastLeague, min, fp, status, tier], i) => ({
    id: i,
    name,
    pos,
    team,
    lastTeam,
    lastLeague,
    min,
    fp,
    status,
    tier,
    gp: lastLeague === "-" ? 0 : 22 + ((i * 3) % 12),
  }),
);
